### ISSUE TITLE
PulseAudio support for CovoxPlayer

### ISSUE THREAD

**Issue by t14462** [yeokm1/covox-music-player#1]
Hello!

I making automat on primitive electronics, which bring "sleeping mode" for my sound system. (Summer overheat protection)

It's simple:
TDA-Amplifier, 4 diodes (Anodes to Left, Cathodes to Right), 4700mf condensator,
Relay+resistor (18k2w) + TRIAC (BT136)

So, I just take 12V from PC power supply, and signal from TV headphones output (or PCs front-panel)

So, It's simple and reliably, but COVOX — is a better way. (I need signal for controlling my device, not listening)

**Comment by yeokm1** [comment]
It definitively possible to write a driver so PulseAudio or ALSA can support the Covox. However I lack the personal resources to pull this off :(

**Comment by kotc** [comment]
hello fellow covoxers, would you kindly test my little project:
https://github.com/kotc/ppsp/ - kernel alsa driver for parallel port audio dongle. since it's alsa, pulseaudio should be able to use it (although i didnt check as i'm sticking to pure alsa on my boxes)
